Add support for .ico/.cur files
nodeca/probe-image-size pull request #42
Opened 2020-10-29 14:33 UTC by leolabs

This PR adds support for .ico and .cur files, which both use the same file structure.

When a given .ico/.cur file contains multiple images, then the largest image's size is returned.

2020-10-29 20:03 UTC, puzrin requested changes
Look reasonable, but see comments.

Also please rebase & squash commits.

2020-10-29 20:03 UTC, puzrin commented on lib/parse_stream/ico.js
> +    parser._bytes(numImages * INDEX_SIZE, function (indexData) {
missed `parser._skipBytes(Infinity);`

2020-10-29 20:03 UTC, puzrin commented on lib/parse_stream/ico.js
> +    if (header !== HEADER || (type !== TYPE_ICO && type !== TYPE_CUR)) {
missed fail if `numImages` === 0;

2020-10-29 21:12 UTC, puzrin commented on lib/parse_stream/ico.js
> +    if (header !== HEADER || type !== TYPE_ICO || !numImages) {
Here still missed `parser._skipBytes(Infinity);`

When you stop analyse content, the rest should be sent to /dev/null. Or you can block other (parallel) parsers.

2020-10-29 21:15 UTC, leolabs commented
Thanks for your quick review! I've made some changes based on your comments and the PR should now be ready to be merged. You can squash all commits into one during the merge using the menu next to the merge button:

<img width="347" alt="Screenshot 2020-10-29 at 22 14 25" src="https://user-images.githubusercontent.com/541628/97633266-1d78a700-1a34-11eb-9472-17eca4e899e1.png">

2020-10-29 21:16 UTC, puzrin commented on package.json
> +    "cur",
remove cur?

2020-10-29 21:24 UTC, puzrin commented
> You can squash all commits into one during the merge using the menu next to the merge button:

I know, but i'd like to see CI results before merge. Because of suspisious tests failure https://travis-ci.org/github/nodeca/probe-image-size/jobs/739931912. I also disabled one tricky test in master. That's why i asked to rebase.

--

In general, everything should be fine now.

2020-10-29 21:32 UTC, leolabs commented
Ah, alright. I've rebased it :)

2020-10-30 04:06 UTC, puzrin approved these changes

2020-10-30 04:07 UTC, merged

2020-10-30 10:53 UTC, puzrin commented
`npm run coverage` - see report.

Could you improve tests coverage for your code? See jpeg tests for example, how to write test vectors with ease (instead of real files).

2020-10-30 18:14 UTC, puzrin commented
See https://github.com/nodeca/probe-image-size/blob/master/test/formats.js#L194

Since it's not convenient tot create real files for all edge cases, we create fake data instead.